### ISSUE TITLE
find a way to translate exports and imports

### ISSUE THREAD

**Issue by ffrank** [ffrank/puppet-mgmtgraph#4]
First, understand the differences between exports as seen by `puppet` vs. `mgmt`.

Then, see if and how exports are even represented in the compiled catalog.

Finally, if possible, see how the translation can be implemented.

**Comment by purpleidea** [comment]
Hi @ffrank Can you elaborate a bit, since my brain is tired and I'm having trouble reading into what you're asking for... Are you asking about exported resources?

**Comment by purpleidea** [comment]
(or alternatively is this a private memo for yourself?)

**Comment by ffrank** [comment]
It is kind of a "note to self", but by all means, if you can expand on the export concept in `mgmt` and how it compares to that in `puppet`, that would be swell!

**Comment by purpleidea** [comment]
On Mon, Jun 6, 2016 at 9:06 AM, Felix Frank <notifications@github.com>
wrote:

> It is kind of a "note to self", but by all means, if you can expand on the
> export concept in mgmt and how it compares to that in puppet, that would
> be swell!
>
It's fairly primitive at the moment in terms of functionality, on the other
hand this is because it hasn't been fully written yet since it will depend
on the DSL. The good news is that it already responds to events, which
makes it effectively instant, where as with puppet you need to wait for
another run.

**Comment by ffrank** [comment]
After putting some more thought into this, it's probably not a good fit after all. Virtual (and exported) resources likely do not become part of the RAL graph, which serves as the basis for translation.

Dropping this one for now.
